"""
PDF Export Service
Generates PDF reports for diagnosis and history
"""

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image as RLImage
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from io import BytesIO
from datetime import datetime
import base64
from pathlib import Path


class PDFGenerator:
    """Generate PDF reports for diagnoses and history"""
    
    INCH = inch
    
    @staticmethod
    def generate_diagnosis_report(diagnosis_data: dict, user_data: dict = None) -> bytes:
        """
        Generate a single diagnosis report as PDF
        
        Args:
            diagnosis_data: Diagnosis record with all details
            user_data: Optional user information
            
        Returns:
            PDF file as bytes
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        elements = []
        
        # Create custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#16a34a'),
            spaceAfter=30,
            alignment=1  # Center
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#15803d'),
            spaceAfter=10,
            spaceBefore=10
        )
        
        # Title
        elements.append(Paragraph("🌾 AgriVoice Diagnosis Report", title_style))
        elements.append(Spacer(1, 0.2*inch))
        
        # Header info
        report_date = datetime.now().strftime("%B %d, %Y at %H:%M")
        elements.append(Paragraph(f"Report Generated: {report_date}", styles['Normal']))
        
        if user_data:
            elements.append(Paragraph(f"Farmer: {user_data.get('full_name', 'Anonymous')}", styles['Normal']))
            if user_data.get('farm_location'):
                elements.append(Paragraph(f"Location: {user_data['farm_location']}", styles['Normal']))
        
        elements.append(Spacer(1, 0.3*inch))
        
        # Diagnosis Details
        elements.append(Paragraph("Diagnosis Question", heading_style))
        elements.append(Paragraph(diagnosis_data.get('query', 'N/A'), styles['Normal']))
        elements.append(Spacer(1, 0.2*inch))
        
        # Detected Tags
        if diagnosis_data.get('detected_tags'):
            elements.append(Paragraph("Detected Issues", heading_style))
            tags_text = ", ".join(diagnosis_data['detected_tags'])
            elements.append(Paragraph(tags_text, styles['Normal']))
            elements.append(Spacer(1, 0.2*inch))
        
        # Diagnosis Text
        elements.append(Paragraph("Diagnosis & Recommendations", heading_style))
        diagnosis_text = diagnosis_data.get('diagnosis_text', 'No diagnosis available')
        elements.append(Paragraph(diagnosis_text, styles['Normal']))
        elements.append(Spacer(1, 0.2*inch))
        
        # Translation if applicable
        if diagnosis_data.get('translated_text'):
            lang = diagnosis_data.get('language', 'unknown')
            elements.append(Paragraph(f"Translation ({lang.upper()})", heading_style))
            elements.append(Paragraph(diagnosis_data['translated_text'], styles['Normal']))
            elements.append(Spacer(1, 0.2*inch))
        
        # Metadata
        elements.append(Paragraph("Report Metadata", heading_style))
        timestamp = diagnosis_data.get('timestamp', 'Unknown')
        elements.append(Paragraph(f"Diagnosis ID: {diagnosis_data.get('id', 'N/A')}", styles['Normal']))
        elements.append(Paragraph(f"Timestamp: {timestamp}", styles['Normal']))
        elements.append(Paragraph(f"Language: {diagnosis_data.get('language', 'en').upper()}", styles['Normal']))
        
        # Footer
        elements.append(Spacer(1, 0.5*inch))
        elements.append(Paragraph(
            "This report was generated by AgriVoice AI-powered crop diagnosis system",
            ParagraphStyle('footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey)
        ))
        
        # Build PDF
        doc.build(elements)
        buffer.seek(0)
        return buffer.getvalue()
    
    @staticmethod
    def generate_history_report(history_records: list, stats: dict, user_data: dict = None) -> bytes:
        """
        Generate a history report with all diagnoses
        
        Args:
            history_records: List of diagnosis records
            stats: Statistics about diagnoses
            user_data: Optional user information
            
        Returns:
            PDF file as bytes
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        elements = []
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#16a34a'),
            spaceAfter=30,
            alignment=1
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#15803d'),
            spaceAfter=10,
            spaceBefore=10
        )
        
        # Title
        elements.append(Paragraph("🌾 AgriVoice Diagnosis History Report", title_style))
        elements.append(Spacer(1, 0.2*inch))
        
        # Header
        report_date = datetime.now().strftime("%B %d, %Y at %H:%M")
        elements.append(Paragraph(f"Report Generated: {report_date}", styles['Normal']))
        
        if user_data:
            elements.append(Paragraph(f"Farmer: {user_data.get('full_name', 'Anonymous')}", styles['Normal']))
            if user_data.get('farm_location'):
                elements.append(Paragraph(f"Location: {user_data['farm_location']}", styles['Normal']))
        
        elements.append(Spacer(1, 0.3*inch))
        
        # Statistics
        if stats:
            elements.append(Paragraph("Summary Statistics", heading_style))
            
            stats_data = [
                ['Total Diagnoses', str(stats.get('total_diagnoses', 0))],
                ['Languages Used', str(len(stats.get('languages_used', {})))],
                ['First Diagnosis', stats.get('first_diagnosis', 'N/A')],
                ['Last Diagnosis', stats.get('last_diagnosis', 'N/A')],
            ]
            
            # Top diseases
            if stats.get('top_diseases'):
                top_disease = stats['top_diseases'][0]
                stats_data.append(['Most Common Issue', f"{top_disease[0]} ({top_disease[1]} times)"])
            
            stats_table = Table(stats_data, colWidths=[2.5*inch, 2.5*inch])
            stats_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#dbeafe')),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            elements.append(stats_table)
            elements.append(Spacer(1, 0.3*inch))
        
        # Diagnosis List
        if history_records:
            elements.append(Paragraph(f"All Diagnoses ({len(history_records)})", heading_style))
            
            for idx, diagnosis in enumerate(history_records, 1):
                elements.append(Spacer(1, 0.1*inch))
                
                # Diagnosis header
                timestamp = diagnosis.get('timestamp', 'Unknown')
                query = diagnosis.get('query', 'N/A')[:100] + "..." if len(diagnosis.get('query', 'N/A')) > 100 else diagnosis.get('query', 'N/A')
                
                elements.append(Paragraph(
                    f"<b>Diagnosis #{idx} - {timestamp}</b>",
                    styles['Normal']
                ))
                
                elements.append(Paragraph(f"Question: {query}", styles['Normal']))
                
                # Tags
                if diagnosis.get('detected_tags'):
                    tags = ", ".join(diagnosis['detected_tags'][:5])
                    elements.append(Paragraph(f"Issues: {tags}", styles['Normal']))
                
                # Short diagnosis preview
                diagnosis_text = diagnosis.get('diagnosis_text', 'N/A')[:150] + "..."
                elements.append(Paragraph(f"<i>{diagnosis_text}</i>", styles['Normal']))
                
                elements.append(Spacer(1, 0.15*inch))
                
                # Page break after every 5 diagnoses
                if idx % 5 == 0 and idx < len(history_records):
                    elements.append(PageBreak())
        
        # Footer
        elements.append(Spacer(1, 0.3*inch))
        elements.append(Paragraph(
            "This report was generated by AgriVoice AI-powered crop diagnosis system",
            ParagraphStyle('footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey)
        ))
        
        # Build PDF
        doc.build(elements)
        buffer.seek(0)
        return buffer.getvalue()


def bytes_to_base64(data: bytes) -> str:
    """Convert bytes to base64 string"""
    return base64.b64encode(data).decode('utf-8')


def save_pdf_to_file(pdf_bytes: bytes, filepath: str) -> bool:
    """
    Save PDF bytes to file
    
    Args:
        pdf_bytes: PDF data as bytes
        filepath: Path to save the PDF
        
    Returns:
        True if successful, False otherwise
    """
    try:
        path = Path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(path, 'wb') as f:
            f.write(pdf_bytes)
        
        return True
    except Exception as e:
        print(f"Error saving PDF: {str(e)}")
        return False
